<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>EbankToInsider</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fe021ce3-fdc6-472d-8b1e-c884ab09594b</testSuiteGuid>
   <testCaseLink>
      <guid>76758412-ff4d-4a80-af81-6775960d9f99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/4.1.Dữ liệu xếp hạng mức độ gắn kết của KH với TPBank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c09ec0a-5869-4903-b400-ccf756485a80</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3b62f97a-907b-40e7-a57f-573fb0ad3a47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/4.2.Khách hàng đã có thẻ credit chưa có Ebank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41bdb982-6fa5-4aac-8247-f47dae569f02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b8a13d0-a9de-44cd-befd-d8ce638e26a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3d5693a-c0ab-4f9a-b462-2d2fe2cd8ece</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b35b0f6e-4f1b-43f7-8695-31bdda73a980</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/4.3.Danh sách KH đăng ký mở thẻ Credit qua Ebank</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>387c66b7-cf8d-4d08-94c5-abce3e812158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1b99c2e-4458-4af7-8a15-e53fda6b56c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a08ba8c-fcd7-4456-8ec3-83ebbefb1d70</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b577821-77ac-4458-9415-3700bf4a208c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/4.4.Nhóm KH shop đã xác thực</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f341890-bc49-463b-83bc-4ded44e99da8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2155a78e-55f4-4572-b8d4-434e3f00d11b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e5c602d-98ba-4525-bc3d-1362bd338407</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
